spring:
  application:
    name: api
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#      ddl-auto: update
#    generate-ddl: true
    show-sql: true
    format-sql: true
server:
  error:
    include-stacktrace: never
  host: ${API_HOST}
  port: ${API_PORT}